server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway
#  data:
#    redis:
##      host: redis
#      host: localhost
#      port: 6379
#  zipkin:
#    base-url: http://localhost:9411

#  sleuth:
#    sampler:
#      probability: 1.0

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          discovery:
            locator:
              enabled: true # auto-register routes from serviceId
              #convert the uppercase Service
#              ID (registered in your Eureka Server) to lowercase
              lower-case-service-id: true
          routes:
            - id: patient-service
              uri: lb://PATIENT-SERVICE
#              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - StripPrefix=0
#                - name: RequestRateLimiter
#                  args:
#                    key-resolver: "#{@ipKeyResolver}"
#                    redis-rate-limiter.replenishRate: 5 # 5 requests per second
#                    redis-rate-limiter.burstCapacity: 10 # max burst capacity
#                    redis-rate-limiter.requestedTokens: 1     # Max tokens the bucket can hold

#                - RewritePath=/api/v1/patients/(?<segment>.*), /api/v1/patients/${segment}
              #removes a specified number of path segments from the beginning of the request URL.
            # Example how StripPrefix works  /patient-service/api/v1/patients --> /api/v1/patients
            #without Eureka RewritePath=/api/v1/patients/(?<segment>.*), /api/v1/patients/${segment}
            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctors/**
              filters:
                - StripPrefix=0

            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointments/**
              filters:
                - StripPrefix=0
#                - name: CircuitBreaker
#                  args:
#                    name: appointmentCB
#                    fallbackUri: forward:/fallback/appointment


#resilience4j:
#  circuitbreaker:
#    instances:
#      appointmentCB:
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#This means:
#  If 50% of calls fail
#  Circuit opens for 5 seconds
#  Then tries again in half-open state