
spring:
  application:
    name: appointment-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: postgres
    password: 7799
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # make sql script delay until schema ready
  sql:
    init:
#      mode: always
      mode: never
      data-locations: classpath*:data.sql
  kafka:
    listener:
      observation-enabled: true
    admin:
      auto-create: true
    bootstrap-servers: localhost:9094
    consumer:
      group-id: appointment-group
      key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
server:
  port: 8083
  servlet:
    context-path: /api/v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
grpc:
  client:
    patientService:
      address: 'static://localhost:9099'
#      address: 'localhost:9099'
      negotiationType: plaintext
#Zipin-Tracing
management:
  tracing:
    sampling:
      probability: 1.0